### ISSUE TITLE
Debugger unhandled exception occuring on non-English symbols

### ISSUE THREAD

**Issue by Makxik** [Samsung/netcoredbg#29] opened 2019-07-29 07:14 UTC
Hello, I'm getting this exception thrown by debugger when I'm trying to debug my 'vscode'-debuggable applications:
`
Console.WriteLine(<some non-English string>);` (App or Debug Console) => Exception: -529697949
`
<set my cursor on non-English element>` => Exception: -529697949
In eventvwr.msc I see... =>
`Application: netcoredbg.exe
CoreCLR Version: 4.6.27817.3
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code e06d7363, exception address 00007FFF873FA839
Stack: `
In ProcessMonitor I see that these DLLs are missing =>
`C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.6\ru-RU\mscorrc.debug.dll
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.6\ru-RU\mscorrc.debug.dll.DLL
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.6\ru\mscorrc.debug.dll
...`

**Comment by viewizard** [comment] 2019-07-31 07:17
@Makxik I can reproduce this issue. Looks like variables evaluation with non-English names works fine (was previously fixed), but evaluation of part of text with non-English word is broken.
Looks like, each time, you set cursor on some text in Console.WriteLine(), VSCode send "evaluate" command to debugger in order to define current "variable" status. Here some tests:

#### Test code with with non-English string and variable with same name:
```
int 你 = 1;
你++;
Console.WriteLine("Test: 你 on this line");
```
vsdbg (first test - variable, second test - part of string with variable name):
```
-> (C) {"command":"evaluate","arguments":{"expression":"你","frameId":1000,"context":"hover"},"type":"request","seq":26}
<- (R) {"seq":69,"type":"response","request_seq":26,"success":true,"command":"evaluate","message":"","body":{"result":"2","type":"int","presentationHint":{"kind":"data","attributes":[]},"variablesReference":0,"memoryReference":"0x0000000000000002"}}
-> (C) {"command":"evaluate","arguments":{"expression":"你","frameId":1000,"context":"hover"},"type":"request","seq":27}
<- (R) {"seq":70,"type":"response","request_seq":27,"success":true,"command":"evaluate","message":"","body":{"result":"2","type":"int","presentationHint":{"kind":"data","attributes":[]},"variablesReference":0,"memoryReference":"0x0000000000000002"}}
```

netcoredbg (first test - variable, second test - part of string with variable name):
```
-> (C) {"command":"evaluate","arguments":{"expression":"你","frameId":35785667510272,"context":"hover"},"type":"request","seq":28}
<- (R) {"body":{"result":"2","type":"int","variablesReference":0},"command":"evaluate","request_seq":28,"seq":51,"success":true,"type":"response"}
-> (C) {"command":"evaluate","arguments":{"expression":"你","frameId":35785667510272,"context":"hover"},"type":"request","seq":29}
<- (R) {"body":{"result":"2","type":"int","variablesReference":0},"command":"evaluate","request_seq":29,"seq":52,"success":true,"type":"response"}
```

#### Test code with with non-English string without variable with same name:
```
Console.WriteLine("Test: 你 on this line");
```
vsdbg:
```
-> (C) {"command":"evaluate","arguments":{"expression":"你","frameId":1000,"context":"hover"},"type":"request","seq":33}
<- (R) {"seq":82,"type":"response","request_seq":33,"success":false,"command":"evaluate","message":"error CS0103: The name '你' does not exist in the current context"}
```
netcoredbg (wrong behavior, should be fixed):
```
-> (C) {"command":"evaluate","arguments":{"expression":"你","frameId":38276748541952,"context":"hover"},"type":"request","seq":28}
<- (R) {"command":"evaluate","message":"System.AggregateException: One or more errors occurred. ('SOS.SymbolReader.ContextVariable' does not contain a definition for '你') ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'SOS.SymbolReader.ContextVariable' does not contain a definition for '你'\n   at CallSite.Target(Closure , CallSite , Object )\n   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)\n   at Submission#0.<<Initialize>>d__0.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)\n   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)\n   --- End of inner exception stack trace ---\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\n   at SOS.SymbolReader.EvalExpression(String expr, IntPtr opaque, IntPtr& errorText, Int32& typeId, Int32& size, IntPtr& result)\n---> (Inner Exception #0) Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'SOS.SymbolReader.ContextVariable' does not contain a definition for '你'\n   at CallSite.Target(Closure , CallSite , Object )\n   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)\n   at Submission#0.<<Initialize>>d__0.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)\n   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)<---\n","request_seq":28,"seq":51,"success":false,"type":"response"}
```

#### Test code with with English string without variable with same name:
```
Console.WriteLine("Test: TEST on this line");
```
vsdbg:
```
-> (C) {"command":"evaluate","arguments":{"expression":"TEST","frameId":1000,"context":"hover"},"type":"request","seq":34}
<- (R) {"seq":83,"type":"response","request_seq":34,"success":false,"command":"evaluate","message":"error CS0103: The name 'TEST' does not exist in the current context"}
```
netcoredbg:
```
-> (C) {"command":"evaluate","arguments":{"expression":"TEST","frameId":40226663694336,"context":"hover"},"type":"request","seq":28}
<- (R) {"command":"evaluate","message":"","request_seq":28,"seq":51,"success":false,"type":"response"}
```

**Comment by viewizard** [comment] 2019-08-01 10:11
Forgot to mention, that I am able to reproduce this issue. All previous test were made on Linux. Windows tests almost the same, except:

#### Test code with non-English string without variable with same name:
```
Console.WriteLine("Test: 你 on this line");
```
netcoredbg (wrong behavior, should be fixed):
```
-> (C) {"command":"evaluate","arguments":{"expression":"你","frameId":19224273616896,"context":"hover"},"type":"request","seq":14}
The pipe program 'netcoredbg.exe' exited unexpectedly with code -529697949.
```

**Comment by enjoycode** [comment] 2020-02-22 07:25
because Console.WriteLine("none-English")  don't use utf8 encoding as OutputEncoding, so netcodedbg's json got exception, it's only support utf8.

**Comment by viewizard** [comment] 2020-07-28 17:16
@Makxik netcoredbg sources was updated with changes, that should fix this issue. Could you please check it?

**Comment by Makxik** [comment] 2020-07-29 02:28
Using latest autogenerated release (65a73c8b633b014b733f70c8dd5dcd9411ec2e75) I got the same "Exception: -529697949" on both Console.WriteLine("non-English") and expression with non-English variable name.

**Comment by viewizard** [comment] 2020-07-29 07:55
> I got the same "Exception: -529697949" on both Console.WriteLine("non-English") and expression with non-English variable name.

We have tests for non-English variable name now and don't have any issues with this case. All works fine in Linux and Tizen. Looks like I also should check Windows, since it probably have different behavior.

**Comment by viewizard** [comment] 2020-07-29 09:54
@Makxik could you please share, launch.json from VSCode you are using, or just part of configuration what you are using for debug session with netcoredbg start.

**Comment by viewizard** [comment] 2020-07-29 18:23
Tested with launch.json:
```
        {
            "name": ".NET Core Launch with netcoredbg",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/netcoreapp3.1/VSCodeTestEvalNotEnglish.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "console": "integratedTerminal",

            "logging": {
                "engineLogging": true
            },

            "pipeTransport": {
                "pipeCwd": "${workspaceFolder}",
                "quoteArgs": false,
                "pipeProgram": "cmd",
                "pipeArgs": ["/c"],
                "debuggerPath": "D:\\projects\\netcoredbg\\bin\\netcoredbg.exe"
            }
        }
```

I found, that VSCode in case of variable with name "당신" provide wrong data to the debugger.
Header ```Content-Length: 127```
But data itself corrupted("??" instead of "당신"), bytes that was read by debugger:
```
{"command":"evaluate","arguments":{"expression":"??","frameId":88201448390656,"context":"hover"},"type":"request","seq":13}
```
and data block have only 123 bytes.
In case of variable with name "你":
Header ```Content-Length: 124```
Bytes that was read by debugger:
```
{"command":"evaluate","arguments":{"expression":"?","frameId":59270548684800,"context":"hover"},"type":"request","seq":13}
```
and data block have only 122 bytes.
Looks like VSCode count size of data block correctly (as for UTF-8, 3 bytes for each character), but send corrupted data.

Also tested MS ```vsdbg.exe``` via pipe (same configuration as for netcoredbg), and got same issue in the same place with:
```
Error from pipe program 'cmd': Error: Invalid protocol message received. Aborting the debug session.
```
This looks like ```vsdbg.exe``` in default debug session configuration have some hidden settings, that should be used for netcoredbg too.

**Comment by Makxik** [comment] 2020-07-30 03:44
My `launch.json`:
```
{
    // Use IntelliSense to find out which attributes exist for C# debugging
    // Use hover for the description of the existing attributes
    // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/bin/Debug/netcoreapp3/${workspaceFolderBasename}.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            // For more information about the 'console' field, see https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#console-terminal-window
            "console": "internalConsole",
            "stopAtEntry": true,
            "internalConsoleOptions": "openOnSessionStart",
            "pipeTransport": {
                "pipeCwd": "${workspaceFolder}",
                "pipeProgram": "cmd",
                "pipeArgs": [
                    "/c"
                ],
                "debuggerPath": "${execPath}\\..\\data\\netcoredbg\\netcoredbg.exe --engineLogging",
                "quoteArgs": true
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}

**Comment by viewizard** [comment] 2020-07-30 08:36
Hmm, you also use "cmd" as a pipe program without any encoding/codepage configuration.

**Comment by viewizard** [comment] 2020-08-19 08:22
Accordingly to omnisharp-vscode extension developer, netcoredbg should have personal debug adapter type and don't use vsdbg's debug adapter type (that work with pipe program). Plus, Windows cmd (conhost.exe) itself don't support work with utf-8, and must not be used with vsdbg's debug adapter type for netcoredbg in case of not English symbols usage in sources/file names.

**Closed by viewizard** 2020-08-19 08:22 UTC
