### ISSUE TITLE
Exception specification in declaration does not match previous declaration

### ISSUE THREAD

**Issue by douglas-wiliam** [Samsung/netcoredbg#43] opened 2020-10-10 16:23 UTC
Kernel: 5.6.19-2-MANJARO

1. I downloaded the package from AUR;

2. I typed in terminal:  makepkg -si

3. And I got the error below: 

```
7/44] Building CXX object src/debug/netcoredbg/CMakeFiles/netcoredbg.dir/manageddebugger.cpp.o

[...]

/home/douglas/Projects/netcoredbg/src/netcoredbg-latest/src/debug/netcoredbg/manageddebugger.cpp:115:7: error: exception specification in declaration does not match previous declaration
pid_t waitpid(pid_t pid, int *status, int options) noexcept
      ^
/usr/include/sys/wait.h:111:16: note: previous declaration is here
extern __pid_t waitpid (__pid_t __pid, int *__stat_loc, int __options);
               ^
1 error generated.
[9/44] Building CXX object src/debug/netcoredbg/CMakeFiles/netcoredbg.dir/symbolreader.cpp.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...

```
Someone can help me? I need to install that in order to use VSCode Debugger.

**Comment by viewizard** [comment] 2020-10-10 16:51
Interesting, why I can't reproduce this issue on Ubuntu. Probably, you could just remove ```#include <sys/wait.h>``` line from manageddebugger.cpp, since we don't really need this header as I see now. Will fix this headers mess in future.

**Comment by douglas-wiliam** [comment] 2020-10-10 19:38
Thank you!! I tried here and it worked :smile: , I made a fork because I needed test this thing asap, but I'll make a pull request for better evaluation for the impacts, until now I got the debugging working without more problems

**Comment by viewizard** [comment] 2020-10-10 19:46
@douglas-wiliam good to hear this news :-).
Don't worry about PR, I already added this changes (and some other headers mess fixes) into internal Samsung git, they will be in public git at next sync (probably will do this next week).

**Comment by viewizard** [comment] 2020-11-25 15:58
Fixed in upstream.

**Closed by viewizard** 2020-11-25 15:58 UTC
