### ISSUE TITLE
"next" cli command causes remainder of program to execute in async method that returns Task<TResult>

### ISSUE THREAD

**Issue by boost1231** [Samsung/netcoredbg#110] opened 2022-12-27 13:30 UTC
## Steps To Reproduce
1. Create a console app with the following code in Program.cs
```
Console.WriteLine("Hello, World!");
await ReturnSomething();
Console.WriteLine("Goodbye World!");

static async Task<int> ReturnSomething()
{
    Console.WriteLine("Start of ReturnSomething()");
    await Task.Delay(1000);
    Console.WriteLine("End of ReturnSometing()");
    return 1;
}
```
2. Set a breakpoint on line 8, `await Task.Delay(1000)`.
3. run
4. when execution stops at the break point, issue the "next" command. Rather than the debugger stopping on line 9, the program executes to completion.

## Notes
- OS: Windows 10
- TargetFramework: net7.0. The issue was also occurring in net6.0.
- I get the same issue when debugging using Netcoredbg in NeoVim
- If the `ReturnSomething` method is changed to just return a Task, rather than Task\<int\>, there are no issues. Stepping works fine.

**Comment by alpencolt** [comment] 2022-12-27 14:59
@boost1231 thank you for report, looks like something wrong with async finite state machine. We'll check it.

**Comment by boost1231** [comment] 2023-04-08 01:10
Just checking to see if this has been worked on.

**Comment by gbalykov** [comment] 2023-04-08 11:55
We didn't have time to look at this yet. Does it still reproduce on the latest release?

**Comment by viewizard** [comment] 2023-04-09 13:13
@gbalykov bug still here, just checked it (-_-).
@boost1231 sorry for the delay, we have a huge amount of work now. Here is the patch, will be in next release in public repo:
```
From 5d14ea8e30661ecbc3635d8f045ddf1da4074152 Mon Sep 17 00:00:00 2001
From: Mikhail Kurinnoi <m.kurinnoi@samsung.com>
Date: Sun, 9 Apr 2023 15:56:42 +0300
Subject: [PATCH] Fix async stepping for Task<TResult>.

---
 src/debugger/stepper_async.cpp | 6 ++++--
 1 file changed, 4 insertions(+), 2 deletions(-)

diff --git a/src/debugger/stepper_async.cpp b/src/debugger/stepper_async.cpp
index ef8f0f4..580f5ce 100644
--- a/src/debugger/stepper_async.cpp
+++ b/src/debugger/stepper_async.cpp
@@ -151,7 +151,8 @@ static HRESULT GetAsyncIdReference(ICorDebugThread *pThread, ICorDebugFrame *pFr
     // Call 'ObjectIdForDebugger' property getter.
     ToRelease<ICorDebugFunction> pFunc;
     IfFailRet(pModule->GetFunctionFromToken(mdObjectIdForDebuggerGetter, &pFunc));
-    IfFailRet(pEvalHelpers->EvalFunction(pThread, pFunc, nullptr, 0, pValue.GetRef(), 1, ppValueAsyncIdRef, defaultEvalFlags));
+    // Note, builder (`this` value) could be generic type - Task<TResult>, type must be provided too.
+    IfFailRet(pEvalHelpers->EvalFunction(pThread, pFunc, pType.GetRef(), 1, pValue.GetRef(), 1, ppValueAsyncIdRef, defaultEvalFlags));
 
     return S_OK;
 }
@@ -230,7 +231,8 @@ static HRESULT SetNotificationForWaitCompletion(ICorDebugThread *pThread, ICorDe
     IfFailRet(pModule->GetFunctionFromToken(setNotifDef, &pFunc));
 
     ICorDebugValue *ppArgsValue[] = {pBuilderValue, pNewBoolean};
-    IfFailRet(pEvalHelpers->EvalFunction(pThread, pFunc, nullptr, 0, ppArgsValue, 2, nullptr, defaultEvalFlags));
+    // Note, builder (`this` value) could be generic type - Task<TResult>, type must be provided too.
+    IfFailRet(pEvalHelpers->EvalFunction(pThread, pFunc, pType.GetRef(), 1, ppArgsValue, 2, nullptr, defaultEvalFlags));
 
     return S_OK;
 }
-- 
2.25.1
```

**Comment by noam-sol** [comment] 2023-06-13 13:39
Thanks @viewizard ! we have come across this bug and this patch seems to solve it. Do you know when the next version with the fix comes out?

**Comment by gbalykov** [comment] 2023-06-13 13:57
@noam-sol we'll try to make new release the next week

**Comment by gbalykov** [comment] 2023-07-07 12:56
This should be fixed in latest release. Feel free to reopen if you see any more related issues.

**Closed by gbalykov** 2023-07-07 12:56 UTC
